export interface ItemOrder {
  Operation: string
  DocNumber: string
  ItmNumber: string
  Material: string
  MatEntrd: string
  PrRefMat: string
  Batch: string
  MatlGroup: string
  ShortText: string
  ItemCateg: string
  ItemType: string
  RelForDe: boolean
  RelForBi: string
  HgLvItem: string
  AlternItm: string
  ReaForRe: string
  ProdHier: string
  OutAgrTa: string
  TargetQty: string
  TargetQu: string
  TUnitIso: string
  TargQtyN: string
  TargQtyD: string
  BaseUom: string
  TBasUnit: string
  ScaleQuan: string
  RoundDlv: string
  ReconDate: any
  MaxDeviat: string
  PoItmNo: string
  CustMat22: string
  MaxDevPe: string
  MaxDevDa: string
  RepairPro: string
  Dlvschedus: string
  DlvGroup: string
  FixedQuan: boolean
  DeliUnlim: boolean
  OverDlvT: string
  UnderDlv: string
  BillBlock: string
  ReplacePt: string
  MethBill: string
  Division: string
  BusArea: string
  NetValue: string
  Currency: string
  CurrenIso: string
  MaxPlDlv: string
  PartDlv: string
  BtchSplit: boolean
  ReqQty: string
  CumReqDe: string
  CumCfQty: string
  CumConQu: string
  SalesUnit: string
  Isocodunit: string
  SalesQty1: string
  SalesQty2: string
  GrossWeig: string
  NetWeight: string
  UnitOfWt: string
  UnitWtiso: string
  Volume: string
  Volumeunit: string
  Volunitiso: string
  CauVbeln: string
  CauPosnr: string
  RefDoc: string
  PosnrVor: string
  ObjCopy: boolean
  UpdatFlag: string
  EndRule: string
  DlvPrio: string
  Plant: string
  StgeLoc: string
  ShipPoint: string
  Route: string
  KeySt: string
  DateSt: any
  NbrSt: string
  StposVbap: string
  OrderProb: string
  CreatDate: string
  CreatedBy: string
  TaxClass1: string
  TaxClass2: string
  TaxClass3: string
  TaxClass4: string
  TaxClass5: string
  TaxClass6: string
  TaxClass7: string
  TaxClass8: string
  TaxClass9: string
  FixSpDay: string
  VarSpDay: string
  PrecDoc: boolean
  NetPrice: string
  CondPUnt: string
  CondUnit: string
  Conisounit: string
  Retoure: boolean
  CashDisc: boolean
  Availcheck: string
  SumRequir: string
  MatPrGrp: string
  AcctAssgt: string
  RebateGrp: string
  CommGroup: string
  EurArtNr: string
  PriceOk: boolean
  ValType: string
  SepValuat: boolean
  BatchMgmt: boolean
  IndBtch: boolean
  MinDely: string
  UpdateGrp: string
  CostDocC: string
  SubtotPp1: string
  SubtotPp2: string
  SubtotPp3: string
  SubtotPp4: string
  SubtotPp5: string
  SubtotPp6: string
  ExchRate: string
  ChOn: string
  EanUpc: string
  FixDate: boolean
  ProfitCtr: string
  PrcGroup1: string
  PrcGroup2: string
  PrcGroup3: string
  PrcGroup4: string
  PrcGroup5: string
  ComponQty: string
  Substreaso: string
  SpecStock: string
  AllocIndi: string
  ProfitSeg: string
  WbsElem: string
  Orderid: string
  PlngMatl: string
  PlngPlant: string
  BaseUnit: string
  Isobasunit: string
  ConvFact: string
  Acctasscat: string
  Consumpt: string
  Bomexplno: string
  ObjNrIt: string
  ResAnal: string
  Reqmtstyp: string
  Credpricit: string
  Partrelid: boolean
  Actcredid: boolean
  CrExchrat: string
  Config: string
  ChclassIn: string
  StatPrice: string
  CondUpdat: boolean
  SernoProf: string
  NoOfSeri: number
  Nogrposted: boolean
  MatGrpSm: string
  ManPrCh: string
  DocCatSd: string
  Matdeterid: string
  Itusageid: string
  Costestnr: string
  CstgVrnt: string
  Bomitemnr: string
  StatVal: string
  StatDate: any
  BusTranst: string
  PrefIndic: string
  Nrcondrec: string
  Intclassnr: string
  BatchExit: string
  BomCatego: string
  BomItNr: string
  Counter: string
  Inconsconf: boolean
  OverhKey: string
  CstgSheet: string
  CstgVrnt1: string
  ProdAlloc: string
  PriceRef: string
  Matpricgrp: string
  Matfrgtgrp: string
  Plandlvsch: string
  Sequenceno: string
  Credpric: string
  PayGuaran: string
  Guranteed: string
  CfopCode: string
  Taxlawicms: string
  Taxlawipi: string
  SdTaxcode: string
  Valcontrnr: string
  Valcontrit: string
  AssortMod: string
  Valspecsto: string
  Matgrhie1: string
  Matgrhie2: string
  Promotion: string
  SalesDeal: string
  Flgleaduni: string
  FreeGoods: string
  ValidObj: string
  TaxAmount: string
  MrpArea: string
  CustMat35: string
  CrExchratV: string
  ExchratestV: string
  PckgNo: string
  MaterialExternal: string
  MaterialGuid: string
  MaterialVersion: string
  MatEntrdExternal: string
  MatEntrdGuid: string
  MatEntrdVersion: string
  PlngMatlExternal: string
  PlngMatlGuid: string
  PlngMatlVersion: string
  PriceRefExternal: string
  PriceRefGuid: string
  PriceRefVersion: string
  PrRefMatExternal: string
  PrRefMatGuid: string
  PrRefMatVersion: string
  MaterialLong: string
  MatEntrdLong: string
  PrRefMatLong: string
  PlngMatlLong: string
  PriceRefLong: string
  DocCatSdLong: string
  editQuantity: boolean
  TargetValCalculate: number
}


export interface ServicesConditions {
  ItmNumber: string
  PckgNo: string
  LineNo: string
  CondStNo: string
  CondCount: string
  CondType: string
  CondValue: string
  Currency: string
  CondUnit: string
  CondPUnt: string
  CurrIso: string
  CdUntIso: string
  Refobjtype: string
  Refobjkey: string
  Reflogsys: string
  Applicatio: string
  Conpricdat: string
  Calctypcon: string
  Conbaseval: string
  Conexchrat: string
  Numconvert: string
  Denominato: string
  Condtype: string
  StatCon: boolean
  Scaletype: string
  Accruals: boolean
  Coninvolst: string
  Condorigin: string
  Groupcond: string
  CondUpdat: boolean
  AccessSeq: string
  Condcount: string
  Roundoffdi: string
  Condvalue: string
  Currency2: string
  CurrIso2: string
  Condcntrl: string
  Condisacti: string
  Condclass: string
  Factbasval: string
  Scalebasin: string
  Scalbasval: string
  Unitmeasur: string
  IsoUnit: string
  Currenckey: string
  Curreniso: string
  Condincomp: boolean
  Condconfig: boolean
  Condchaman: boolean
}

export interface Service {
  PckgNo: string
  LineNo: string
  ExtLine: string
  OutlLevel: number
  OutlNo: string
  OutlInd: string
  SubpckgNo: string
  DeleteInd: string
  Service: string
  ServType: string
  Edition: string
  SscItem: string
  ExtServ: string
  Quantity: string
  BaseUom: string
  UomIso: string
  OvfTol: string
  OvfUnlim: boolean
  PriceUnit: string
  GrossVal: string
  NetValue: string
  FromLine: string
  ToLine: string
  ShortText: string
  Distrib: string
  PersNo: string
  Wagetype: string
  PlnPckg: string
  PlnLine: string
  ConPckg: string
  ConLine: string
  TmpPckg: string
  TmpLine: string
  SscLim: boolean
  LimitLine: string
  ActualQty: string
  ActualVal: string
  ConValue: string
  ConQty: string
  TargetVal: string
  UnplVal: string
  UnplQty: string
  BaslineNo: string
  BasicLine: string
  Alternat: string
  Bidder: string
  SuppLine: string
  OpenQty: string
  Inform: string
  Blanket: string
  Eventual: string
  TaxCode: string
  Taxjurcode: string
  PriceChg: boolean
  MatlGroup: string
  NondItax: string
  Date: any
  Begintime: string
  Endtime: string
  ExtpersNo: string
  Formula: string
  FormVal1: string
  FormVal2: string
  FormVal3: string
  FormVal4: string
  FormVal5: string
  Userf1Num: string
  Userf2Num: string
  Userf1Txt: string
  Userf2Txt: string
  GrPrice: string
  HiLineNo: string
  Extdes: string
  Bosgrp: string
  Bosinter: string
  RiskLine: string
  SupplNo: string
  SupplStatus: string
  ObjType: string
  SiLine: string
  MiLineNo: string
  QtRel: string
  LotSize: boolean,
  children?: Service[]
}

export interface Conditions {
  ItmNumber: string
  CondStNo: string
  CondCount: string
  CondType: string
  CondValue: string
  Currency: string
  CondUnit: string
  CondPUnt: string
  Calctypcon: string
  Conexchrat: string
  Numconvert: string
  Denominato: string
  Accountkey: string
}

export interface Partners {
  PartnRole: string 
  PartnNumb: string
  ItmNumber: string
  Name: string 
  Name2: string 
  Street: string 
  Country: string 
  CountrIso: string 
  PostlCode: string 
  City: string 
  Region: string 
  Telephone: string 
  Address: string 
}

export interface MessageERP {
  Type: string
  Id: string
  Number: string
  Message: string
  LogNo: string
  LogMsgNo: string
  MessageV1: string
  MessageV2: string
  MessageV3: string
  MessageV4: string
  Parameter: string
  Row: number
  Field: string
  System: string
  typeMessage: string
  descMessage : string
}

